import { IRentalItem } from '@shared/types';

export const mockRentItems: IRentalItem[] = [
  {
    id: 1,
    title: 'Ремонт квартир под ключ',
    cost: { payment: 134, priceUnit: 'день' },
    category: { id: 1, name: 'Ремонт' },
    productType: 'service',
    reviewCount: 12,
    address: 'Р-н Советский',
    rating: 4.5,
    previewImage: {
      id: 1,
      url: 'https://avatars.dzeninfra.ru/get-zen_doc/271828/pub_6672b69ac44ca74a3aa7ded9_6672b7d4867ea0000933d652/scale_1200',
    },
    description: 'Ремонт под ключ с гарантией качества: быстро, аккуратно и по доступной цене.',
    createdDate: '2025-12-20',
  },
  {
    id: 2,
    title: 'Аренда велосипедов',
    cost: { payment: 500, priceUnit: 'час' },
    category: { id: 2, name: 'Спорт' },
    productType: 'product',
    reviewCount: 23,
    address: 'Центральный р-н',
    rating: 4.7,
    previewImage: {
      id: 2,
      url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    },
    description: 'Городские велосипеды для прогулок по городу. Шлем в комплекте.',
    createdDate: '2026-01-15',
  },
  {
    id: 3,
    title: 'Фотостудия для мероприятий',
    cost: { payment: 2500, priceUnit: 'час' },
    category: { id: 3, name: 'Фото/Видео' },
    productType: 'space',
    reviewCount: 42,
    address: 'Ленинский проспект, 45',
    rating: 4.9,
    previewImage: {
      id: 3,
      url: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400',
    },
    description: 'Профессиональная фотостудия с оборудованием, фонами и световыми приборами.',
    createdDate: '2026-01-10',
  },
  {
    id: 4,
    title: 'Аренда перфоратора Bosch',
    cost: { payment: 800, priceUnit: 'день' },
    category: { id: 4, name: 'Инструменты' },
    productType: 'product',
    reviewCount: 34,
    address: 'Р-н Октябрьский',
    rating: 4.8,
    previewImage: {
      id: 4,
      url: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400',
    },
    description: 'Мощный перфоратор Bosch GBH 2-26 DRE. Идеален для сверления бетона, кирпича, камня.',
    createdDate: '2026-02-10',
  },
  {
    id: 5,
    title: 'Конференц-зал на 20 человек',
    cost: { payment: 1200, priceUnit: 'час' },
    category: { id: 5, name: 'Офис' },
    productType: 'space',
    reviewCount: 31,
    address: 'Бизнес-центр "Плаза"',
    rating: 4.6,
    previewImage: {
      id: 5,
      url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=400',
    },
    description: 'Современный конференц-зал с проектором, экраном и системой видеоконференций.',
    createdDate: '2026-01-18',
  },
  {
    id: 6,
    title: 'Репетитор по математике',
    cost: { payment: 800, priceUnit: 'час' },
    category: { id: 6, name: 'Образование' },
    productType: 'service',
    reviewCount: 27,
    address: 'Университетский район',
    rating: 4.9,
    previewImage: {
      id: 6,
      url: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=400',
    },
    description: 'Подготовка к ЕГЭ и ОГЭ, устранение пробелов, решение олимпиадных задач.',
    createdDate: '2026-01-12',
  },
  {
    id: 7,
    title: 'Уютная квартира-студия',
    cost: { payment: 3500, priceUnit: 'день' },
    category: { id: 7, name: 'Жильё' },
    productType: 'space',
    reviewCount: 58,
    address: 'Проспект Мира, 12',
    rating: 4.7,
    previewImage: {
      id: 7,
      url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400',
    },
    description: 'Уютная студия в центре города, всё необходимое для комфортного проживания.',
    createdDate: '2026-02-01',
  },
  {
    id: 8,
    title: 'Аренда автомобильного прицепа',
    cost: { payment: 1500, priceUnit: 'день' },
    category: { id: 8, name: 'Транспорт' },
    productType: 'product',
    reviewCount: 9,
    address: 'Р-н Кировский',
    rating: 4.3,
    previewImage: {
      id: 8,
      url: 'https://images.unsplash.com/photo-1558618047-f4e70a784e80?w=400',
    },
    description: 'Прицеп грузоподъёмностью 750 кг. Подходит для перевозки мебели и стройматериалов.',
    createdDate: '2026-02-15',
  },
];
