import { IRentalDetail } from '@shared/types';

const makeHours = (from: number, to: number): boolean[] =>
  Array.from({ length: 24 }, (_, i) => i >= from && i < to);

export const mockRentAd: IRentalDetail[] = [
  {
    id: 1,
    title: 'Ремонт квартир под ключ',
    cost: { payment: 134, priceUnit: 'день' },
    category: { id: 1, name: 'Ремонт' },
    productType: 'service',
    address: 'Красноярский край, г. Красноярск, Р-н Советский, ул. Краснодарская, 406',
    rating: 4.5,
    reviewCount: 12,
    previewImage: {
      id: 1,
      url: 'https://avatars.dzeninfra.ru/get-zen_doc/271828/pub_6672b69ac44ca74a3aa7ded9_6672b7d4867ea0000933d652/scale_1200',
    },
    description: 'Ремонт под ключ с гарантией качества: быстро, аккуратно и по доступной цене. Работаем с любыми видами отделочных материалов.',
    createdDate: '2025-12-20',
    media: [
      { id: 1, url: 'https://avatars.dzeninfra.ru/get-zen_doc/271828/pub_6672b69ac44ca74a3aa7ded9_6672b7d4867ea0000933d652/scale_1200' },
    ],
    renter: {
      id: 1,
      name: 'Thomas Selby',
      rating: 4.2,
      reviewCount: 142,
      avatar: { id: 2, url: 'https://i.pravatar.cc/150?img=1' },
    },
    reviews: 12,
    coordinates: '56.0760,92.9230',
    bookingCalendar: '2026-01-01 – 2026-12-31',
    booking: {
      availabilityRange: { start: '2026-01-01', end: '2026-12-31' },
      autoRenewal: true,
      enabledDays: ['mon', 'tue', 'wed', 'thu', 'fri'],
      schedule: [
        { day: 'mon', hours: makeHours(8, 18), minDuration: 4 },
        { day: 'tue', hours: makeHours(8, 18), minDuration: 4 },
        { day: 'wed', hours: makeHours(8, 18), minDuration: 4 },
        { day: 'thu', hours: makeHours(8, 18), minDuration: 4 },
        { day: 'fri', hours: makeHours(8, 17), minDuration: 4 },
      ],
    },
  },
  {
    id: 2,
    title: 'Аренда велосипедов',
    cost: { payment: 500, priceUnit: 'час' },
    category: { id: 2, name: 'Спорт' },
    productType: 'product',
    address: 'Красноярский край, г. Красноярск, Центральный р-н, пр. Мира, 70',
    rating: 4.7,
    reviewCount: 23,
    previewImage: {
      id: 2,
      url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    },
    description: 'Городские велосипеды для прогулок по городу. Шлем в комплекте, замок предоставляется. Есть велосипеды для взрослых и детей.',
    createdDate: '2026-01-15',
    media: [
      { id: 2, url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600' },
    ],
    renter: {
      id: 2,
      name: 'Анна Смирнова',
      rating: 4.8,
      reviewCount: 67,
      avatar: { id: 3, url: 'https://i.pravatar.cc/150?img=5' },
    },
    reviews: 23,
    coordinates: '56.0184,92.8672',
    bookingCalendar: '2026-04-01 – 2026-10-31',
    booking: {
      availabilityRange: { start: '2026-04-01', end: '2026-10-31' },
      autoRenewal: false,
      enabledDays: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'],
      schedule: [
        { day: 'mon', hours: makeHours(9, 21), minDuration: 1 },
        { day: 'tue', hours: makeHours(9, 21), minDuration: 1 },
        { day: 'wed', hours: makeHours(9, 21), minDuration: 1 },
        { day: 'thu', hours: makeHours(9, 21), minDuration: 1 },
        { day: 'fri', hours: makeHours(9, 21), minDuration: 1 },
        { day: 'sat', hours: makeHours(8, 22), minDuration: 1 },
        { day: 'sun', hours: makeHours(8, 22), minDuration: 1 },
      ],
    },
  },
  {
    id: 3,
    title: 'Фотостудия для мероприятий',
    cost: { payment: 2500, priceUnit: 'час' },
    category: { id: 3, name: 'Фото/Видео' },
    productType: 'space',
    address: 'Красноярский край, г. Красноярск, Ленинский проспект, 45',
    rating: 4.9,
    reviewCount: 42,
    previewImage: {
      id: 3,
      url: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400',
    },
    description: 'Профессиональная фотостудия с оборудованием, фонами и световыми приборами. Площадь 80 кв.м., 3 съёмочных зоны.',
    createdDate: '2026-01-10',
    media: [
      { id: 3, url: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600' },
    ],
    renter: {
      id: 3,
      name: 'Павел Фотограф',
      rating: 4.9,
      reviewCount: 210,
      avatar: { id: 4, url: 'https://i.pravatar.cc/150?img=8' },
    },
    reviews: 42,
    coordinates: '56.0103,92.8506',
    bookingCalendar: '2026-01-01 – 2026-12-31',
    booking: {
      availabilityRange: { start: '2026-01-01', end: '2026-12-31' },
      autoRenewal: true,
      enabledDays: ['tue', 'wed', 'thu', 'fri', 'sat', 'sun'],
      schedule: [
        { day: 'tue', hours: makeHours(10, 22), minDuration: 2 },
        { day: 'wed', hours: makeHours(10, 22), minDuration: 2 },
        { day: 'thu', hours: makeHours(10, 22), minDuration: 2 },
        { day: 'fri', hours: makeHours(10, 22), minDuration: 2 },
        { day: 'sat', hours: makeHours(9, 23), minDuration: 2 },
        { day: 'sun', hours: makeHours(9, 20), minDuration: 2 },
      ],
    },
  },
  {
    id: 4,
    title: 'Аренда перфоратора Bosch',
    cost: { payment: 800, priceUnit: 'день' },
    category: { id: 4, name: 'Инструменты' },
    productType: 'product',
    address: 'Красноярский край, г. Красноярск, Р-н Октябрьский, ул. Высотная, 15',
    rating: 4.8,
    reviewCount: 34,
    previewImage: {
      id: 4,
      url: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400',
    },
    description: 'Мощный перфоратор Bosch GBH 2-26 DRE. Идеален для сверления бетона, кирпича, камня. Бурение отверстий диаметром до 26 мм.',
    createdDate: '2026-02-10',
    media: [
      { id: 4, url: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=600' },
    ],
    renter: {
      id: 4,
      name: 'Елена Петрова',
      rating: 4.9,
      reviewCount: 87,
      avatar: { id: 5, url: 'https://i.pravatar.cc/150?img=9' },
    },
    reviews: 34,
    coordinates: '56.0090,92.7900',
    bookingCalendar: '2026-01-01 – 2026-12-31',
    booking: {
      availabilityRange: { start: '2026-01-01', end: '2026-12-31' },
      autoRenewal: true,
      enabledDays: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat'],
      schedule: [
        { day: 'mon', hours: makeHours(8, 20), minDuration: 1 },
        { day: 'tue', hours: makeHours(8, 20), minDuration: 1 },
        { day: 'wed', hours: makeHours(8, 20), minDuration: 1 },
        { day: 'thu', hours: makeHours(8, 20), minDuration: 1 },
        { day: 'fri', hours: makeHours(8, 20), minDuration: 1 },
        { day: 'sat', hours: makeHours(9, 18), minDuration: 1 },
      ],
    },
  },
  {
    id: 5,
    title: 'Конференц-зал на 20 человек',
    cost: { payment: 1200, priceUnit: 'час' },
    category: { id: 5, name: 'Офис' },
    productType: 'space',
    address: 'Красноярский край, г. Красноярск, Бизнес-центр "Плаза", ул. Карла Маркса, 95',
    rating: 4.6,
    reviewCount: 31,
    previewImage: {
      id: 5,
      url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=400',
    },
    description: 'Современный конференц-зал с проектором, экраном и системой видеоконференций. Wi-Fi, кофемашина, маркерная доска.',
    createdDate: '2026-01-18',
    media: [
      { id: 5, url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=600' },
    ],
    renter: {
      id: 5,
      name: 'Офис-Центр Плаза',
      rating: 4.5,
      reviewCount: 112,
      avatar: { id: 6, url: 'https://i.pravatar.cc/150?img=12' },
    },
    reviews: 31,
    coordinates: '56.0120,92.8750',
    bookingCalendar: '2026-01-01 – 2026-12-31',
    booking: {
      availabilityRange: { start: '2026-01-01', end: '2026-12-31' },
      autoRenewal: true,
      enabledDays: ['mon', 'tue', 'wed', 'thu', 'fri'],
      schedule: [
        { day: 'mon', hours: makeHours(8, 20), minDuration: 2 },
        { day: 'tue', hours: makeHours(8, 20), minDuration: 2 },
        { day: 'wed', hours: makeHours(8, 20), minDuration: 2 },
        { day: 'thu', hours: makeHours(8, 20), minDuration: 2 },
        { day: 'fri', hours: makeHours(8, 18), minDuration: 2 },
      ],
    },
  },
  {
    id: 6,
    title: 'Репетитор по математике',
    cost: { payment: 800, priceUnit: 'час' },
    category: { id: 6, name: 'Образование' },
    productType: 'service',
    address: 'Красноярский край, г. Красноярск, Университетский район, ул. Академика Киренского, 26',
    rating: 4.9,
    reviewCount: 27,
    previewImage: {
      id: 6,
      url: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=400',
    },
    description: 'Подготовка к ЕГЭ и ОГЭ, устранение пробелов, решение олимпиадных задач. Онлайн или очно.',
    createdDate: '2026-01-12',
    media: [
      { id: 6, url: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=600' },
    ],
    renter: {
      id: 6,
      name: 'Дмитрий Иванов',
      rating: 5.0,
      reviewCount: 45,
      avatar: { id: 7, url: 'https://i.pravatar.cc/150?img=15' },
    },
    reviews: 27,
    coordinates: '56.0075,92.8195',
    bookingCalendar: '2026-01-01 – 2026-12-31',
    booking: {
      availabilityRange: { start: '2026-01-01', end: '2026-12-31' },
      autoRenewal: true,
      enabledDays: ['mon', 'wed', 'fri', 'sat'],
      schedule: [
        { day: 'mon', hours: makeHours(15, 20), minDuration: 1 },
        { day: 'wed', hours: makeHours(15, 20), minDuration: 1 },
        { day: 'fri', hours: makeHours(15, 20), minDuration: 1 },
        { day: 'sat', hours: makeHours(10, 18), minDuration: 1 },
      ],
    },
  },
  {
    id: 7,
    title: 'Уютная квартира-студия',
    cost: { payment: 3500, priceUnit: 'день' },
    category: { id: 7, name: 'Жильё' },
    productType: 'space',
    address: 'Красноярский край, г. Красноярск, Проспект Мира, 12',
    rating: 4.7,
    reviewCount: 58,
    previewImage: {
      id: 7,
      url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400',
    },
    description: 'Уютная студия в центре города, всё необходимое для комфортного проживания. Полностью оборудованная кухня, стиральная машина, быстрый Wi-Fi.',
    createdDate: '2026-02-01',
    media: [
      { id: 7, url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600' },
    ],
    renter: {
      id: 7,
      name: 'Мария Козлова',
      rating: 4.8,
      reviewCount: 93,
      avatar: { id: 8, url: 'https://i.pravatar.cc/150?img=20' },
    },
    reviews: 58,
    coordinates: '56.0171,92.8563',
    bookingCalendar: '2026-04-01 – 2026-12-31',
    booking: {
      availabilityRange: { start: '2026-04-01', end: '2026-12-31' },
      autoRenewal: false,
      enabledDays: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'],
      schedule: [
        { day: 'mon', hours: makeHours(0, 24), minDuration: 24 },
        { day: 'tue', hours: makeHours(0, 24), minDuration: 24 },
        { day: 'wed', hours: makeHours(0, 24), minDuration: 24 },
        { day: 'thu', hours: makeHours(0, 24), minDuration: 24 },
        { day: 'fri', hours: makeHours(0, 24), minDuration: 24 },
        { day: 'sat', hours: makeHours(0, 24), minDuration: 24 },
        { day: 'sun', hours: makeHours(0, 24), minDuration: 24 },
      ],
    },
  },
  {
    id: 8,
    title: 'Аренда автомобильного прицепа',
    cost: { payment: 1500, priceUnit: 'день' },
    category: { id: 8, name: 'Транспорт' },
    productType: 'product',
    address: 'Красноярский край, г. Красноярск, Р-н Кировский, ул. Шахтёров, 55',
    rating: 4.3,
    reviewCount: 9,
    previewImage: {
      id: 8,
      url: 'https://images.unsplash.com/photo-1558618047-f4e70a784e80?w=400',
    },
    description: 'Прицеп грузоподъёмностью 750 кг. Подходит для перевозки мебели и стройматериалов. Требуется залог 3000 руб.',
    createdDate: '2026-02-15',
    media: [
      { id: 8, url: 'https://images.unsplash.com/photo-1558618047-f4e70a784e80?w=600' },
    ],
    renter: {
      id: 8,
      name: 'Сергей Волков',
      rating: 4.4,
      reviewCount: 22,
      avatar: { id: 9, url: 'https://i.pravatar.cc/150?img=25' },
    },
    reviews: 9,
    coordinates: '56.0230,92.8100',
    bookingCalendar: '2026-03-01 – 2026-12-31',
    booking: {
      availabilityRange: { start: '2026-03-01', end: '2026-12-31' },
      autoRenewal: false,
      enabledDays: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat'],
      schedule: [
        { day: 'mon', hours: makeHours(8, 19), minDuration: 1 },
        { day: 'tue', hours: makeHours(8, 19), minDuration: 1 },
        { day: 'wed', hours: makeHours(8, 19), minDuration: 1 },
        { day: 'thu', hours: makeHours(8, 19), minDuration: 1 },
        { day: 'fri', hours: makeHours(8, 19), minDuration: 1 },
        { day: 'sat', hours: makeHours(9, 17), minDuration: 1 },
      ],
    },
  },
];
